=== pedromanoel/EbitSim/simulations/BitTorrentTracker.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT contentList (content+)>
<!ELEMENT content (numOfPieces,numOfSubPieces,subPieceSize)>
<!ELEMENT numOfPieces (#PCDATA)>
<!ELEMENT numOfSubPieces (#PCDATA)>
<!ELEMENT subPieceSize (#PCDATA)>
<!ATTLIST content name ID #REQUIRED>

=== pedromanoel/EbitSim/simulations/BTContents.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contentList SYSTEM "BitTorrentTracker.dtd">
<contentList>
   <content name="test1">
      <numOfPieces>80</numOfPieces>
      <numOfSubPieces>8</numOfSubPieces>
      <subPieceSize>32768</subPieceSize>
   </content>
   <content name="test_simple">
      <numOfPieces>10</numOfPieces>
      <numOfSubPieces>8</numOfSubPieces>
      <subPieceSize>32768</subPieceSize>
   </content>
</contentList>
